将鱼图像数据进行操作，使用numpy知识

# Pandas的数据结构



导入pandas：  
三剑客

In [8]:
import numpy as np

#SPSS(900M,IBM————>EXCEL),SAS
import pandas as pd
# dataframe 相当于excel
from pandas import Series,DataFrame

import matplotlib.pyplot as plt

%matplotlib inline

### 1、Series

Series是一种类似与一维数组的对象，由下面两个部分组成：
- values：一组数据（ndarray类型）
- index：相关的数据索引标签

In [9]:
v = np.random.randint(0,150,size=10)
v

array([ 48,  31, 143,  74,  36, 137, 132,  17,  56,  96])

#### 1）Series的创建

两种创建方式：

(1) 由列表或numpy数组创建

    默认索引为0到N-1的整数型索引

In [10]:
s = Series(data = v, index = ['a','b','c','d','e','f','h','g','j','k'])
s

a     48
b     31
c    143
d     74
e     36
f    137
h    132
g     17
j     56
k     96
dtype: int32

    还可以通过设置index参数指定索引

特别地，由ndarray创建的是引用，而不是副本。对Series元素的改变也会改变原来的ndarray对象中的元素。（列表没有这种情况）

(2) 由字典创建

In [11]:
s2 = Series(data = {'a':10,'b':100,'c':1024})
s2


a      10
b     100
c    1024
dtype: int64

In [13]:
# pandas 基于numpy
s.any()

True

In [14]:
s.sum()

770

In [15]:
# 方差
s.std()

47.17579416984473

In [16]:
s.min()

17

In [17]:
s.argmin()

c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 'argmin' is deprecated, use 'idxmin' instead. The behavior of 'argmin'
will be corrected to return the positional minimum in the future.
Use 'series.values.argmin' to get the position of the minimum now.
  """Entry point for launching an IPython kernel.


'g'

In [18]:
s['g']

17

In [19]:
s

a     48
b     31
c    143
d     74
e     36
f    137
h    132
g     17
j     56
k     96
dtype: int32

In [21]:
s['b'] = 74
s['k'] = 74

In [22]:
s

a     48
b     74
c    143
d     74
e     36
f    137
h    132
g     17
j     56
k     74
dtype: int32

In [20]:
s.unique()

array([ 48,  31, 143,  74,  36, 137, 132,  17,  56,  96], dtype=int64)

In [23]:
# 去重
s.unique()

array([ 48,  74, 143,  36, 137, 132,  17,  56], dtype=int64)

In [27]:
# Series封装了ndarrary
nd = s.values
# nd.unique()

np.unique(nd)
# series 是一维的，只能是一维的！!!
#dataframe 

array([ 17,  36,  48,  56,  74, 132, 137, 143])

============================================

练习1：

使用多种方法创建以下Series，命名为s1：  
语文 150   
数学 150   
英语 150   
理综 300   

============================================

#### 2）Series的索引和切片

可以使用中括号取单个索引（此时返回的是元素类型），或者中括号里一个列表取多个索引（此时返回的仍然是一个Series类型）。分为显示索引和隐式索引：

(1) 显式索引：

    - 使用index中的元素作为索引值
    - 使用.loc[]（推荐）

 注意，此时是闭区间

(2) 隐式索引：

    - 使用整数作为索引值
    - 使用.iloc[]（推荐）

 注意，此时是半开区间

In [38]:
s[0]

48

In [40]:
s.iloc[[1,3,0,5]]

b     74
d     74
a     48
f    137
dtype: int32

In [42]:
s.loc['a':'d']

a     48
b     74
c    143
d     74
dtype: int32

In [41]:
# 左闭右开
s.iloc[0:3]

a     48
b     74
c    143
dtype: int32

In [32]:
nd[3]

74

In [28]:
# ndarray
s['k']

74

In [33]:
s.loc['a']

48

In [34]:
s.loc['a','b','c']

IndexingError: Too many indexers

In [35]:
s.loc[['a','b','c']]

a     48
b     74
c    143
dtype: int32

In [36]:
s['a':'d']

a     48
b     74
c    143
d     74
dtype: int32

In [37]:
s.loc['a':'d']

a     48
b     74
c    143
d     74
dtype: int32

============================================

练习2：

使用多种方法对练习1创建的Series s1进行索引和切片：

索引：
数学 150 

切片：
语文 150 
数学 150 
英语 150 

============================================

#### 3）Series的基本概念

可以把Series看成一个定长的有序字典

可以通过shape，size，index,values等得到series的属性

In [43]:
s.shape

(10,)

In [44]:
s.size

10

In [45]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'h', 'g', 'j', 'k'], dtype='object')

In [46]:
s.values

array([ 48,  74, 143,  74,  36, 137, 132,  17,  56,  74])

In [47]:
s.dtype

dtype('int32')

可以通过head(),tail()快速查看Series对象的样式

In [50]:
s.head(3)

a     48
b     74
c    143
dtype: int32

In [49]:
s.tail()

f    137
h    132
g     17
j     56
k     74
dtype: int32

当索引没有对应的值时，可能出现缺失数据显示NaN（not a number）的情况

In [51]:
s

a     48
b     74
c    143
d     74
e     36
f    137
h    132
g     17
j     56
k     74
dtype: int32

In [52]:
# NAN 就是not a number
s['e'] = np.NAN

In [54]:
s['k'] = np.NaN
s

a     48.0
b     74.0
c    143.0
d     74.0
e      NaN
f    137.0
h    132.0
g     17.0
j     56.0
k      NaN
dtype: float64

In [55]:
s['a'] = np.nan
s

a      NaN
b     74.0
c    143.0
d     74.0
e      NaN
f    137.0
h    132.0
g     17.0
j     56.0
k      NaN
dtype: float64

可以使用pd.isnull()，pd.notnull()，或自带isnull(),notnull()函数检测缺失数据

In [56]:
pd.isnull(s)

a     True
b    False
c    False
d    False
e     True
f    False
h    False
g    False
j    False
k     True
dtype: bool

In [60]:
cond = pd.notnull(s)
cond

a    False
b     True
c     True
d     True
e    False
f     True
h     True
g     True
j     True
k    False
dtype: bool

In [61]:
s[cond]

b     74.0
c    143.0
d     74.0
f    137.0
h    132.0
g     17.0
j     56.0
dtype: float64

Series对象本身及其实例都有一个name属性

In [62]:
s2 = Series(nd,index=list('abcdefghjk'),name='python')
s2

a     48
b     74
c    143
d     74
e     36
f    137
g    132
h     17
j     56
k     74
Name: python, dtype: int32

#### 4）Series的运算

(1) 适用于numpy的数组运算也适用于Series

In [63]:
s


a      NaN
b     74.0
c    143.0
d     74.0
e      NaN
f    137.0
h    132.0
g     17.0
j     56.0
k      NaN
dtype: float64

In [64]:
# 必然方法，升级，求和，如果有空值，运算时，空值==0
s.sum()

633.0

In [66]:
nd = s.values
nd.sum()

nan

In [67]:
s + 10

a      NaN
b     84.0
c    153.0
d     84.0
e      NaN
f    147.0
h    142.0
g     27.0
j     66.0
k      NaN
dtype: float64

In [68]:
# 调用方法的形式，空值参与运算
s.add(100,fill_value=0)

a    100.0
b    174.0
c    243.0
d    174.0
e    100.0
f    237.0
h    232.0
g    117.0
j    156.0
k    100.0
dtype: float64

(2) Series之间的运算

- 在运算中自动对齐不同索引的数据
- 如果索引不对应，则补NaN

- 注意：要想保留所有的index，则需要使用.add()函数

In [69]:
s

a      NaN
b     74.0
c    143.0
d     74.0
e      NaN
f    137.0
h    132.0
g     17.0
j     56.0
k      NaN
dtype: float64

In [70]:
s2

a     48
b     74
c    143
d     74
e     36
f    137
g    132
h     17
j     56
k     74
Name: python, dtype: int32

In [71]:
s + s2

a      NaN
b    148.0
c    286.0
d    148.0
e      NaN
f    274.0
g    149.0
h    149.0
j    112.0
k      NaN
dtype: float64

In [72]:
s.add(s2,fill_value=0)

a     48.0
b    148.0
c    286.0
d    148.0
e     36.0
f    274.0
g    149.0
h    149.0
j    112.0
k     74.0
dtype: float64

In [74]:
s3 = Series(np.random.randint(0,150,size=5),index=['a','b','w','p','q'])
s3

a     71
b     42
w    117
p     45
q      6
dtype: int32

In [77]:
np.nan -1024

nan

In [76]:
np.NAN + 10

nan

In [75]:
# s2 s3 运算时对不齐的数据，填补： nan + 任何数都是空
s2 + s3

a    119.0
b    116.0
c      NaN
d      NaN
e      NaN
f      NaN
g      NaN
h      NaN
j      NaN
k      NaN
p      NaN
q      NaN
w      NaN
dtype: float64

In [78]:
s2.sub(s3,fill_value=0)

a    -23.0
b     32.0
c    143.0
d     74.0
e     36.0
f    137.0
g    132.0
h     17.0
j     56.0
k     74.0
p    -45.0
q     -6.0
w   -117.0
dtype: float64

============================================

练习3：

1. 想一想Series运算和ndarray运算的规则有什么不同？

2. 新建另一个索引包含“文综”的Series s2，并与s2进行多种算术操作。思考如何保存所有数据。

============================================

### 2、DataFrame

DataFrame是一个【表格型】的数据结构，可以看做是【由Series组成的字典】（共用同一个索引）。DataFrame由按一定顺序排列的多列数据组成。设计初衷是将Series的使用场景从一维拓展到二维。DataFrame既有行索引，也有列索引。
- 行索引：index
- 列索引：columns
- 值：values（numpy的二维数组）

#### 1）DataFrame的创建
最常用的方法是传递一个字典来创建。DataFrame以字典的键作为每一【列】的名称，以字典的值（一个数组）作为每一列。

此外，DataFrame会自动加上每一行的索引（和Series一样）。

同Series一样，若传入的列与字典的键不匹配，则相应的值为NaN。


In [79]:
# dataframe 是多个series组成， 共用index（行索引）
df = DataFrame(data=np.random.randint(0,150,size=(10,3)),index=list('abcdefhijk'),columns=['python','math','en'])
df

python  math   en
a     148    92   71
b      54     2   80
c     110    82   22
d      48   141   53
e     100    13   83
f     108   126   13
h      83    98   44
i     110    83   95
j       5   100  120
k     102   121  109

DataFrame属性：values、columns、index、shape

In [80]:
df.shape
# (10——》0 代表行——》样本 ,3——》1 代表列——》属性)

(10, 3)

In [81]:
df.values

array([[148,  92,  71],
       [ 54,   2,  80],
       [110,  82,  22],
       [ 48, 141,  53],
       [100,  13,  83],
       [108, 126,  13],
       [ 83,  98,  44],
       [110,  83,  95],
       [  5, 100, 120],
       [102, 121, 109]])

In [83]:
df.columns = ['Py','Math','En']

In [84]:
df

Py  Math   En
a  148    92   71
b   54     2   80
c  110    82   22
d   48   141   53
e  100    13   83
f  108   126   13
h   83    98   44
i  110    83   95
j    5   100  120
k  102   121  109

In [85]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'h', 'i', 'j', 'k'], dtype='object')

In [108]:
df['Py']

a    148
b     54
c    110
d     48
e    100
f    108
h     83
i    110
j      5
k    102
Name: Py, dtype: int32

============================================

练习4：

根据以下考试成绩表，创建一个DataFrame，命名为df：
```
    张三  李四
语文 150  0
数学 150  0
英语 150  0
理综 300  0
```

============================================

#### 2）DataFrame的索引

(1) 对列进行索引

    - 通过类似字典的方式
    - 通过属性的方式

 可以将DataFrame的列获取为一个Series。返回的Series拥有原DataFrame相同的索引，且name属性也已经设置好了，就是相应的列名。

In [92]:
# 列>行


In [109]:
df['Math']

a     92
b      2
c     82
d    141
e     13
f    126
h     98
i     83
j    100
k    121
Name: Math, dtype: int32

In [110]:
df[['Py','Math']]

Py  Math
a  148    92
b   54     2
c  110    82
d   48   141
e  100    13
f  108   126
h   83    98
i  110    83
j    5   100
k  102   121

In [113]:
df['En']

a     71
b     80
c     22
d     53
e     83
f     13
h     44
i     95
j    120
k    109
Name: En, dtype: int32

In [112]:
df[['En']]

En
a   71
b   80
c   22
d   53
e   83
f   13
h   44
i   95
j  120
k  109

In [114]:
# 列是DataFrame 的属性
df.En

a     71
b     80
c     22
d     53
e     83
f     13
h     44
i     95
j    120
k    109
Name: En, dtype: int32

(2) 对行进行索引

    - 使用.ix[]来进行行索引
    - 使用.loc[]加index来进行行索引
    - 使用.iloc[]加整数来进行行索引
    
 同样返回一个Series，index为原来的columns。

In [115]:
df.loc['a']

Py      148
Math     92
En       71
Name: a, dtype: int32

In [116]:
df.loc[['a','b']]

Py  Math  En
a  148    92  71
b   54     2  80

In [117]:
df.iloc[0]

Py      148
Math     92
En       71
Name: a, dtype: int32

In [118]:
df.iloc[[0,1,3]]

Py  Math  En
a  148    92  71
b   54     2  80
d   48   141  53

In [119]:
df.loc['a':'e']

Py  Math  En
a  148    92  71
b   54     2  80
c  110    82  22
d   48   141  53
e  100    13  83

In [120]:
df.iloc[0:4]

Py  Math  En
a  148    92  71
b   54     2  80
c  110    82  22
d   48   141  53

In [125]:
# 对列 ， 进行切片
# !!!(切片的时候，直接使用[]————》代表对行，进行切片，无法使用[]对列进行切片)
df['Py':'En']

Empty DataFrame
Columns: [Py, Math, En]
Index: []

In [124]:
df['a':'e']

Py  Math  En
a  148    92  71
b   54     2  80
c  110    82  22
d   48   141  53
e  100    13  83

In [129]:
# !!!对列进行切片
df.iloc[:,1:3]

Math   En
a    92   71
b     2   80
c    82   22
d   141   53
e    13   83
f   126   13
h    98   44
i    83   95
j   100  120
k   121  109

(3) 对元素索引的方法
    - 使用列索引
    - 使用行索引(iloc[3,1]相当于两个参数;iloc[[3,3]] 里面的[3,3]看做一个参数)
    - 使用values属性（二维numpy数组）

In [130]:
df

Py  Math   En
a  148    92   71
b   54     2   80
c  110    82   22
d   48   141   53
e  100    13   83
f  108   126   13
h   83    98   44
i  110    83   95
j    5   100  120
k  102   121  109

In [133]:
df['Math']['c']

82

In [134]:
df.loc['c']['Math']

82

In [135]:
df.loc['c','Math']

82

In [ ]:
# !!!语法错误
# 因为数据（0,1）
df['Math','c']

In [ ]:
# Series 和DataFrame 基于numpy
# 知识点比较琐碎
# 记知识，考练习

【注意】
直接用中括号时：
- 索引表示的是列索引
- 切片表示的是行切片

============================================

练习5：

使用多种方法对ddd进行索引和切片，并比较其中的区别

============================================

#### 3）DataFrame的运算

（1） DataFrame之间的运算

同Series一样：

- 在运算中自动对齐不同索引的数据
- 如果索引不对应，则补NaN

创建DataFrame df1 不同人员的各科目成绩，月考一

创建DataFrame df2 不同人员的各科目成绩，月考二  
有新学生转入

下面是Python 操作符与pandas操作函数的对应表：

| Python Operator | Pandas Method(s)                      |
|-----------------|---------------------------------------|
| ``+``           | ``add()``                             |
| ``-``           | ``sub()``, ``subtract()``             |
| ``*``           | ``mul()``, ``multiply()``             |
| ``/``           | ``truediv()``, ``div()``, ``divide()``|
| ``//``          | ``floordiv()``                        |
| ``%``           | ``mod()``                             |
| ``**``          | ``pow()``                             |


（2） Series与DataFrame之间的运算

【重要】

- 使用Python操作符：以行为单位操作（参数必须是行），对所有行都有效。（类似于numpy中二维数组与一维数组的运算，但可能出现NaN）

- 使用pandas操作函数：

        axis=0：以列为单位操作（参数必须是列），对所有列都有效。
        axis=1：以行为单位操作（参数必须是行），对所有行都有效。

============================================

练习6：

1. 假设ddd是期中考试成绩，ddd2是期末考试成绩，请自由创建ddd2，并将其与ddd相加，求期中期末平均值。

2. 假设张三期中考试数学被发现作弊，要记为0分，如何实现？

3. 李四因为举报张三作弊立功，期中考试所有科目加100分，如何实现？

4. 后来老师发现有一道题出错了，为了安抚学生情绪，给每位学生每个科目都加10分，如何实现？

============================================